# -*- coding: utf-8 -*-
"""Language translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7-YGnvgqUfLm9E9PBOwucoS38FwrzFL
"""

pip install transformers sentencepiece

from transformers import MarianMTModel, MarianTokenizer

def translate_name(name, src_lang="en", tgt_lang="fr"):
    model_name = f"Helsinki-NLP/opus-mt-{src_lang}-{tgt_lang}"

    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model = MarianMTModel.from_pretrained(model_name)

    input_tokens = tokenizer.prepare_seq2seq_batch([name], return_tensors="pt")
    translation = model.generate(**input_tokens)
    translated = tokenizer.decode(translation[0], skip_special_tokens=True)

    return translated

name = " my name is Narmadha"

# Translate to French, Spanish, German, Hindi, Tamil
print("French:", translate_name(name, "en", "fr"))
print("Spanish:", translate_name(name, "en", "es"))
print("German:", translate_name(name, "en", "de"))
print("Hindi:", translate_name(name, "en", "hi"))
# print("Tamil:", translate_name(name, "en", "ta"))